# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true

    Specs:
      - Hostname: orderer1
        SANS:
          - "{{.Hostname}}.{{.Domain}}"
          - 127.0.0.1
      - Hostname: orderer2
        SANS:
          - "{{.Hostname}}.{{.Domain}}"
          - 127.0.0.1
      - Hostname: orderer3
        SANS:
          - "{{.Hostname}}.{{.Domain}}"
          - 127.0.0.1

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  - Name: Org1
    Domain: org1.example.com
    EnableNodeOUs: true

    Template:
      Count: 2
      Start: 1
      SANS:
        - "{{.Hostname}}.{{.Domain}}"
        - 127.0.0.1

    Users:
      Count: 1000

  - Name: Org2
    Domain: org2.example.com
    EnableNodeOUs: true

    Template:
      Count: 2
      Start: 1
      SANS:
        - "{{.Hostname}}.{{.Domain}}"
        - 127.0.0.1

    Users:
      Count: 1000
