#!/usr/bin/env bash

set -eu
set -o pipefail

export X_FABRIC_ORG=orderer

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

. ${SCRIPT_DIR}/../lib/setenv
. ${SCRIPT_DIR}/../lib/utils
. ${SCRIPT_DIR}/../lib/install
. ${SCRIPT_DIR}/../lib/certificate
. ${SCRIPT_DIR}/../lib/channel

check_root

add_hosts

install_deps
install_fabric_binaries
install_fabric_ca_server
install_fabric_ca_client

register_and_enroll_user_tls orderer orderer ${X_ORDERER_HOST}
register_and_enroll_user admin ordereradmin

install_fabric_orderer

prompt_copy_msp_and_tls_files
wait_msp_and_tls_files

create_genesis_block
prompt_copy_genesis_block

create_channel

log_info "👉 Fabric Orderer setup completed!"
