#!/usr/bin/env bash

set -eu
set -o pipefail

function log_info {
  echo -e "\e[32m${1}\e[0m"
}

function log_warning {
  echo -e "\e[1;33m${1}\e[0m"
}

function log_error {
  echo -e "\e[31m${1}\e[0m"
}

function command_exists {
	command -v "$@" > /dev/null 2>&1
}

function check_root {
  if [[ $(id -u) -ne 0 ]]; then
    log_error "Must run as root user"
    exit 1
  fi
}
